#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright 2026 Bogdan Shapovalov and the Fury authors
#
# Install the freshly built shell into /Applications, and leave exactly one
# Fury behind.
#
#     tools/release/install-macos.sh
#
# WHY THIS IS A SCRIPT. Every step here was done by hand, three times, and the
# machine ended up with two Fury icons every time -- reported three times, and
# twice I blamed the wrong thing before measuring. The cause is dull: `tauri
# build` writes target/release/bundle/macos/Fury.app, LaunchServices registers
# any application bundle it sees, and Spotlight then offers two. Unregistering
# it works until the next build recreates it.
#
# So the build copy is DELETED rather than unregistered. It is a build artifact,
# regenerated by the next build in seconds, and the only way it stops coming
# back is not being there.
#
# The temporary volumes are the same story with a different source: bundle_dmg.sh
# mounts a scratch image while making the .dmg, and a stale /Volumes/dmg.XXXX
# entry survives the unmount in the LaunchServices database. Three of them had
# accumulated.
#
# What is deliberately NOT touched: core.bundle. That is the browser itself, it
# is registered too, and it is genuinely a second application -- see
# core/build/build.sh for why hiding it properly needs a package extension
# rather than a delete.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
built="$here/target/release/bundle/macos/Fury.app"
dest="/Applications/Fury.app"
LSREGISTER=/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister

[ -d "$built" ] || { echo "!! no build at $built -- run: cd desktop && npm run app:build" >&2; exit 1; }

echo "== closing Fury if it is running"
osascript -e 'quit app "Fury"' 2>/dev/null || true
sleep 2
# The agent outlives the window on purpose, and holds the socket the next one
# wants. Same reason the Windows installer has a hook for this.
pkill -f 'Fury.app/Contents/MacOS/fury-' 2>/dev/null || true
sleep 1

echo "== installing"
rm -rf "$dest"
cp -R "$built" "$dest"

# Ad-hoc, and this is a stopgap rather than the answer. `tauri build` without an
# identity leaves the bundle unsigned -- Sealed Resources=none -- which is fine
# locally and refused by Gatekeeper the moment the file is downloaded, with "is
# damaged" and no mention of a signature. Signing here at least makes the
# locally installed copy valid; a distributable build needs a Developer ID and
# tools/release/sign-shell.sh.
codesign --force --deep --sign - "$dest" >/dev/null 2>&1
codesign -v --deep --strict "$dest" 2>&1 && echo "   signature valid"

echo "== leaving one Fury"
rm -rf "$built"
"$LSREGISTER" -u "$built" 2>/dev/null || true
# Stale scratch volumes from bundle_dmg.sh, and any real one left mounted.
"$LSREGISTER" -dump 2>/dev/null | awk '/path: *\/Volumes\/.*Fury\.app/ { print $2 }' | sort -u |
  while read -r v; do "$LSREGISTER" -u "$v" 2>/dev/null || true; done
for v in /Volumes/Fury /Volumes/dmg.*; do
  [ -e "$v" ] || "$LSREGISTER" -u "$v" 2>/dev/null || true
done

echo "== what the system knows about now"
"$LSREGISTER" -dump 2>/dev/null | grep -i "path:.*Fury" | grep -v Helper | grep -v furycrm | sort -u | sed 's/^/   /'

open -a "$dest"
echo
echo "installed $(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$dest/Contents/Info.plist") and launched"
