#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright 2026 Bogdan Shapovalov and the Fury authors
#
# Install the freshly built shell into /Applications, and leave exactly one
# Fury behind.
#
#     tools/release/install-macos.sh
#
# WHY THIS IS A SCRIPT. Every step here was done by hand, three times, and the
# machine ended up with two Fury icons every time -- reported three times, and
# twice I blamed the wrong thing before measuring. The cause is dull: `tauri
# build` writes target/release/bundle/macos/Fury.app, LaunchServices registers
# any application bundle it sees, and Spotlight then offers two. Unregistering
# it works until the next build recreates it.
#
# So the build copy is DELETED rather than unregistered. It is a build artifact,
# regenerated by the next build in seconds, and the only way it stops coming
# back is not being there.
#
# The temporary volumes are the same story with a different source: bundle_dmg.sh
# mounts a scratch image while making the .dmg, and a stale /Volumes/dmg.XXXX
# entry survives the unmount in the LaunchServices database. Three of them had
# accumulated.
#
# What is deliberately NOT touched: core.bundle. That is the browser itself, it
# is registered too, and it is genuinely a second application -- see
# core/build/build.sh for why hiding it properly needs a package extension
# rather than a delete.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
built="$here/target/release/bundle/macos/Fury.app"
dest="/Applications/Fury.app"
LSREGISTER=/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister

[ -d "$built" ] || { echo "!! no build at $built -- run: cd desktop && npm run app:build" >&2; exit 1; }

# A scratch image left mounted by an interrupted build.
#
# bundle_dmg.sh mounts one while making the .dmg and detaches it at the end. A
# build that dies in between leaves it mounted, and the NEXT build then fails at
# the packaging step with nothing but "failed to run bundle_dmg.sh" -- met on
# 17.08.2026. It also registers its copy of Fury.app, which is one of the ways
# two of them keep appearing.
for v in /Volumes/dmg.*; do
  [ -d "$v" ] || continue
  echo "== detaching a leftover build volume: $v"
  hdiutil detach "$v" -quiet 2>/dev/null || hdiutil detach "$v" -force >/dev/null 2>&1 || true
done
rm -f "$here/target/release/bundle/macos"/rw.*.dmg

echo "== closing Fury if it is running"
osascript -e 'quit app "Fury"' 2>/dev/null || true
sleep 2
# The agent outlives the window on purpose, and holds the socket the next one
# wants. Same reason the Windows installer has a hook for this.
pkill -f 'Fury.app/Contents/MacOS/fury-' 2>/dev/null || true
sleep 1

echo "== installing"
rm -rf "$dest"
# ditto, not cp -R: it is what Apple documents for copying a bundle, and it
# carries extended attributes and symlinks across rather than flattening them.
ditto "$built" "$dest"

# NOT re-signed when there is a signature worth keeping. This used to run
# `codesign --force --deep --sign -` unconditionally, which was harmless while
# every build was ad-hoc and became destructive on 21.09.2026, when builds
# started carrying a Developer ID: it replaces that signature with an anonymous
# one and throws away the stapled notarisation ticket, so the copy in
# /Applications is treated as an unidentified developer's while the very same
# build downloaded from the release page is not.
#
# The ad-hoc fallback stays for the ordinary case it was written for: `tauri
# build` with no identity leaves the bundle unsigned, which is fine locally and
# refused by Gatekeeper the moment the file is downloaded. A distributable
# build needs tools/release/sign-shell.sh.
if codesign -v --deep --strict "$dest" 2>/dev/null; then
  team="$(codesign -dv --verbose=2 "$dest" 2>&1 | sed -n 's/^TeamIdentifier=//p')"
  if xcrun stapler validate "$dest" >/dev/null 2>&1; then
    echo "   signature kept: valid, notarised, team ${team:-none}"
  else
    echo "   signature kept: valid, not notarised, team ${team:-none}"
  fi
else
  echo "   no valid signature to keep — signing ad-hoc so it opens here"
  codesign --force --deep --sign - "$dest" >/dev/null 2>&1
  codesign -v --deep --strict "$dest" 2>&1 && echo "   ad-hoc signature valid"
fi

echo "== leaving one Fury"
rm -rf "$built"
"$LSREGISTER" -u "$built" 2>/dev/null || true
# Stale scratch volumes from bundle_dmg.sh, and any real one left mounted.
"$LSREGISTER" -dump 2>/dev/null | awk '/path: *\/Volumes\/.*Fury\.app/ { print $2 }' | sort -u |
  while read -r v; do "$LSREGISTER" -u "$v" 2>/dev/null || true; done
for v in /Volumes/Fury /Volumes/dmg.*; do
  [ -e "$v" ] || "$LSREGISTER" -u "$v" 2>/dev/null || true
done

echo "== what the system knows about now"
"$LSREGISTER" -dump 2>/dev/null | grep -i "path:.*Fury" | grep -v Helper | grep -v furycrm | sort -u | sed 's/^/   /'

open -a "$dest"
echo
echo "installed $(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$dest/Contents/Info.plist") and launched"
