// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright 2026 Bogdan Shapovalov and the Fury authors

//! What a browser in a given country says about its languages.
//!
//! GENERATED by tools/locale-table/generate.py from the Chromium tree. Do not
//! edit by hand — rerun the generator after a Chromium bump, and read its diff.
//!
//! 250 countries, from CLDR territoryInfo composed with Chrome's own
//! 58 shipped UI locales and the 54 IDS_ACCEPT_LANGUAGES
//! values it ships with them. A country whose language Chrome does not ship a
//! UI for resolves to en-US and "en-US,en", because that is what Chrome
//! itself does there — not because we ran out of ideas.
//!
//! Why this exists: a profile leaving through Berlin while announcing
//! `en-US,en` is one subtraction away from being flagged, the same subtraction
//! that catches a wrong timezone. The timezone already follows the exit; this
//! is the other half.
//!
//! Why it is a table and not a guess: "which language do they speak in X" is a
//! question people answer confidently and wrongly. Every row here is Chrome's
//! own answer.

/// A country's browser locale: what Chrome would be installed as, and what it
/// would send.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Locale {
    /// The UI locale, suitable for `--lang`. One of Chrome's shipped locales,
    /// so a .pak for it exists.
    pub ui: &'static str,
    /// navigator.languages, in order. The Accept-Language header is generated
    /// from this by the core, so the two cannot disagree.
    pub languages: &'static [&'static str],
}

/// ISO 3166-1 alpha-2, uppercase, sorted — the form the exit resolver returns.
static BY_COUNTRY: &[(&str, &str, &[&str])] = &[
    ("AD", "ca", &["ca-ES", "ca"]),
    ("AE", "ar", &["ar", "en-US", "en"]),
    ("AF", "fa", &["fa", "en-US", "en"]),
    ("AG", "en-GB", &["en-GB", "en-US", "en"]),
    ("AI", "en-GB", &["en-GB", "en-US", "en"]),
    ("AL", "en-US", &["en-US", "en"]),
    ("AM", "en-US", &["en-US", "en"]),
    ("AO", "pt-PT", &["pt-PT", "pt", "en-US", "en"]),
    ("AR", "es-419", &["es-419", "es"]),
    ("AS", "en-GB", &["en-GB", "en-US", "en"]),
    ("AT", "de", &["de-DE", "de", "en-US", "en"]),
    ("AU", "en-GB", &["en-GB", "en-US", "en"]),
    ("AW", "nl", &["nl-NL", "nl", "en-US", "en"]),
    ("AX", "sv", &["sv-SE", "sv", "en-US", "en"]),
    ("AZ", "en-US", &["en-US", "en"]),
    ("BA", "hr", &["hr-HR", "hr", "en-US", "en"]),
    ("BB", "en-GB", &["en-GB", "en-US", "en"]),
    ("BD", "bn", &["bn-IN", "bn", "en-US", "en"]),
    ("BE", "nl", &["nl-NL", "nl", "en-US", "en"]),
    ("BF", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("BG", "bg", &["bg-BG", "bg"]),
    ("BH", "ar", &["ar", "en-US", "en"]),
    ("BI", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("BJ", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("BL", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("BM", "en-GB", &["en-GB", "en-US", "en"]),
    ("BN", "ms", &["en-US", "en"]),
    ("BO", "es-419", &["es-419", "es"]),
    ("BQ", "nl", &["nl-NL", "nl", "en-US", "en"]),
    ("BR", "pt-BR", &["pt-BR", "pt", "en-US", "en"]),
    ("BS", "en-GB", &["en-GB", "en-US", "en"]),
    ("BT", "en-US", &["en-US", "en"]),
    ("BW", "en-GB", &["en-GB", "en-US", "en"]),
    ("BY", "ru", &["ru-RU", "ru", "en-US", "en"]),
    ("BZ", "en-GB", &["en-GB", "en-US", "en"]),
    ("CA", "en-GB", &["en-GB", "en-US", "en"]),
    ("CC", "en-GB", &["en-GB", "en-US", "en"]),
    ("CD", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("CF", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("CG", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("CH", "de", &["de-DE", "de", "en-US", "en"]),
    ("CI", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("CK", "en-GB", &["en-GB", "en-US", "en"]),
    ("CL", "es-419", &["es-419", "es"]),
    ("CM", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("CN", "zh-CN", &["zh-CN", "zh"]),
    ("CO", "es-419", &["es-419", "es"]),
    ("CQ", "en-GB", &["en-GB", "en-US", "en"]),
    ("CR", "es-419", &["es-419", "es"]),
    ("CU", "es-419", &["es-419", "es"]),
    ("CV", "pt-PT", &["pt-PT", "pt", "en-US", "en"]),
    ("CW", "nl", &["nl-NL", "nl", "en-US", "en"]),
    ("CX", "en-GB", &["en-GB", "en-US", "en"]),
    ("CY", "el", &["el-GR", "el"]),
    ("CZ", "cs", &["cs-CZ", "cs"]),
    ("DE", "de", &["de-DE", "de", "en-US", "en"]),
    ("DG", "en-GB", &["en-GB", "en-US", "en"]),
    ("DJ", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("DK", "da", &["da-DK", "da", "en-US", "en"]),
    ("DM", "en-GB", &["en-GB", "en-US", "en"]),
    ("DO", "es-419", &["es-419", "es"]),
    ("DZ", "ar", &["ar", "en-US", "en"]),
    ("EA", "es-419", &["es-419", "es"]),
    ("EC", "es-419", &["es-419", "es"]),
    ("EE", "et", &["et-EE", "et", "en-US", "en"]),
    ("EG", "ar", &["ar", "en-US", "en"]),
    ("EH", "ar", &["ar", "en-US", "en"]),
    ("ER", "en-GB", &["en-GB", "en-US", "en"]),
    ("ES", "es", &["es-ES", "es"]),
    ("ET", "am", &["am", "en-GB", "en"]),
    ("FI", "fi", &["fi-FI", "fi", "en-US", "en"]),
    ("FJ", "en-GB", &["en-GB", "en-US", "en"]),
    ("FK", "en-GB", &["en-GB", "en-US", "en"]),
    ("FM", "en-GB", &["en-GB", "en-US", "en"]),
    ("FO", "en-US", &["en-US", "en"]),
    ("FR", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("GA", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("GB", "en-GB", &["en-GB", "en-US", "en"]),
    ("GD", "en-GB", &["en-GB", "en-US", "en"]),
    ("GE", "en-US", &["en-US", "en"]),
    ("GF", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("GG", "en-GB", &["en-GB", "en-US", "en"]),
    ("GH", "en-GB", &["en-GB", "en-US", "en"]),
    ("GI", "en-GB", &["en-GB", "en-US", "en"]),
    ("GL", "en-US", &["en-US", "en"]),
    ("GM", "en-GB", &["en-GB", "en-US", "en"]),
    ("GN", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("GP", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("GQ", "es-419", &["es-419", "es"]),
    ("GR", "el", &["el-GR", "el"]),
    ("GS", "en-GB", &["en-GB", "en-US", "en"]),
    ("GT", "es-419", &["es-419", "es"]),
    ("GU", "en-GB", &["en-GB", "en-US", "en"]),
    ("GW", "pt-PT", &["pt-PT", "pt", "en-US", "en"]),
    ("GY", "en-GB", &["en-GB", "en-US", "en"]),
    ("HK", "zh-TW", &["zh-TW", "zh", "en-US", "en"]),
    ("HN", "es-419", &["es-419", "es"]),
    ("HR", "hr", &["hr-HR", "hr", "en-US", "en"]),
    ("HT", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("HU", "hu", &["hu-HU", "hu", "en-US", "en"]),
    ("IC", "es-419", &["es-419", "es"]),
    ("ID", "id", &["id-ID", "id", "en-US", "en"]),
    ("IE", "en-GB", &["en-GB", "en-US", "en"]),
    ("IL", "he", &["he-IL", "he", "en-US", "en"]),
    ("IM", "en-GB", &["en-GB", "en-US", "en"]),
    ("IN", "hi", &["hi-IN", "hi", "en-US", "en"]),
    ("IO", "en-GB", &["en-GB", "en-US", "en"]),
    ("IQ", "ar", &["ar", "en-US", "en"]),
    ("IR", "fa", &["fa", "en-US", "en"]),
    ("IS", "en-US", &["en-US", "en"]),
    ("IT", "it", &["it-IT", "it", "en-US", "en"]),
    ("JE", "en-GB", &["en-GB", "en-US", "en"]),
    ("JM", "en-GB", &["en-GB", "en-US", "en"]),
    ("JO", "ar", &["ar", "en-US", "en"]),
    ("JP", "ja", &["ja", "en-US", "en"]),
    ("KE", "sw", &["sw", "en-GB", "en"]),
    ("KG", "ru", &["ru-RU", "ru", "en-US", "en"]),
    ("KH", "en-US", &["en-US", "en"]),
    ("KI", "en-GB", &["en-GB", "en-US", "en"]),
    ("KM", "ar", &["ar", "en-US", "en"]),
    ("KN", "en-GB", &["en-GB", "en-US", "en"]),
    ("KP", "ko", &["ko-KR", "ko", "en-US", "en"]),
    ("KR", "ko", &["ko-KR", "ko", "en-US", "en"]),
    ("KW", "ar", &["ar", "en-US", "en"]),
    ("KY", "en-GB", &["en-GB", "en-US", "en"]),
    ("KZ", "ru", &["ru-RU", "ru", "en-US", "en"]),
    ("LA", "en-US", &["en-US", "en"]),
    ("LB", "ar", &["ar", "en-US", "en"]),
    ("LC", "en-GB", &["en-GB", "en-US", "en"]),
    ("LI", "de", &["de-DE", "de", "en-US", "en"]),
    ("LK", "ta", &["ta-IN", "ta", "en-US", "en"]),
    ("LR", "en-US", &["en-US", "en"]),
    ("LS", "en-GB", &["en-GB", "en-US", "en"]),
    ("LT", "lt", &["lt", "en-US", "en", "ru", "pl"]),
    ("LU", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("LV", "lv", &["lv-LV", "lv", "en-US", "en"]),
    ("LY", "ar", &["ar", "en-US", "en"]),
    ("MA", "ar", &["ar", "en-US", "en"]),
    ("MC", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("MD", "ro", &["ro-RO", "ro", "en-US", "en"]),
    ("ME", "sr", &["sr-RS", "sr", "en-US", "en"]),
    ("MF", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("MG", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("MH", "en-GB", &["en-GB", "en-US", "en"]),
    ("MK", "en-US", &["en-US", "en"]),
    ("ML", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("MM", "en-US", &["en-US", "en"]),
    ("MN", "en-US", &["en-US", "en"]),
    ("MO", "zh-TW", &["zh-TW", "zh", "en-US", "en"]),
    ("MP", "en-GB", &["en-GB", "en-US", "en"]),
    ("MQ", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("MR", "ar", &["ar", "en-US", "en"]),
    ("MS", "en-GB", &["en-GB", "en-US", "en"]),
    ("MT", "en-GB", &["en-GB", "en-US", "en"]),
    ("MU", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("MV", "en-US", &["en-US", "en"]),
    ("MW", "en-GB", &["en-GB", "en-US", "en"]),
    ("MX", "es-419", &["es-419", "es"]),
    ("MY", "ms", &["en-US", "en"]),
    ("MZ", "pt-PT", &["pt-PT", "pt", "en-US", "en"]),
    ("NA", "en-GB", &["en-GB", "en-US", "en"]),
    ("NC", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("NE", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("NF", "en-GB", &["en-GB", "en-US", "en"]),
    ("NG", "en-GB", &["en-GB", "en-US", "en"]),
    ("NI", "es-419", &["es-419", "es"]),
    ("NL", "nl", &["nl-NL", "nl", "en-US", "en"]),
    ("NO", "nb", &["nb-NO", "nb", "no", "nn", "en-US", "en"]),
    ("NP", "en-US", &["en-US", "en"]),
    ("NR", "en-GB", &["en-GB", "en-US", "en"]),
    ("NU", "en-GB", &["en-GB", "en-US", "en"]),
    ("NZ", "en-GB", &["en-GB", "en-US", "en"]),
    ("OM", "ar", &["ar", "en-US", "en"]),
    ("PA", "es-419", &["es-419", "es"]),
    ("PE", "es-419", &["es-419", "es"]),
    ("PF", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("PG", "en-GB", &["en-GB", "en-US", "en"]),
    ("PH", "en-US", &["en-US", "en"]),
    ("PK", "ur", &["en-US", "en"]),
    ("PL", "pl", &["pl-PL", "pl", "en-US", "en"]),
    ("PM", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("PN", "en-GB", &["en-GB", "en-US", "en"]),
    ("PR", "es-419", &["es-419", "es"]),
    ("PS", "ar", &["ar", "en-US", "en"]),
    ("PT", "pt-PT", &["pt-PT", "pt", "en-US", "en"]),
    ("PW", "en-GB", &["en-GB", "en-US", "en"]),
    ("PY", "es-419", &["es-419", "es"]),
    ("QA", "ar", &["ar", "en-US", "en"]),
    ("RE", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("RO", "ro", &["ro-RO", "ro", "en-US", "en"]),
    ("RS", "sr", &["sr-RS", "sr", "en-US", "en"]),
    ("RU", "ru", &["ru-RU", "ru", "en-US", "en"]),
    ("RW", "en-GB", &["en-GB", "en-US", "en"]),
    ("SA", "ar", &["ar", "en-US", "en"]),
    ("SB", "en-GB", &["en-GB", "en-US", "en"]),
    ("SC", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("SD", "ar", &["ar", "en-US", "en"]),
    ("SE", "sv", &["sv-SE", "sv", "en-US", "en"]),
    ("SG", "en-GB", &["en-GB", "en-US", "en"]),
    ("SH", "en-GB", &["en-GB", "en-US", "en"]),
    ("SI", "sl", &["sl-SI", "sl", "en-GB", "en"]),
    ("SJ", "nb", &["nb-NO", "nb", "no", "nn", "en-US", "en"]),
    ("SK", "sk", &["sk-SK", "sk", "cs", "en-US", "en"]),
    ("SL", "en-GB", &["en-GB", "en-US", "en"]),
    ("SM", "it", &["it-IT", "it", "en-US", "en"]),
    ("SN", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("SO", "ar", &["ar", "en-US", "en"]),
    ("SR", "nl", &["nl-NL", "nl", "en-US", "en"]),
    ("SS", "en-GB", &["en-GB", "en-US", "en"]),
    ("ST", "pt-PT", &["pt-PT", "pt", "en-US", "en"]),
    ("SV", "es-419", &["es-419", "es"]),
    ("SX", "en-GB", &["en-GB", "en-US", "en"]),
    ("SY", "ar", &["ar", "en-US", "en"]),
    ("SZ", "en-GB", &["en-GB", "en-US", "en"]),
    ("TC", "en-GB", &["en-GB", "en-US", "en"]),
    ("TD", "ar", &["ar", "en-US", "en"]),
    ("TG", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("TH", "th", &["th-TH", "th"]),
    ("TJ", "en-US", &["en-US", "en"]),
    ("TK", "en-GB", &["en-GB", "en-US", "en"]),
    ("TL", "pt-PT", &["pt-PT", "pt", "en-US", "en"]),
    ("TM", "en-US", &["en-US", "en"]),
    ("TN", "ar", &["ar", "en-US", "en"]),
    ("TO", "en-GB", &["en-GB", "en-US", "en"]),
    ("TR", "tr", &["tr-TR", "tr", "en-US", "en"]),
    ("TT", "en-GB", &["en-GB", "en-US", "en"]),
    ("TV", "en-GB", &["en-GB", "en-US", "en"]),
    ("TW", "zh-TW", &["zh-TW", "zh", "en-US", "en"]),
    ("TZ", "sw", &["sw", "en-GB", "en"]),
    ("UA", "uk", &["uk-UA", "uk", "en-US", "en"]),
    ("UG", "sw", &["sw", "en-GB", "en"]),
    ("UM", "en-GB", &["en-GB", "en-US", "en"]),
    ("US", "en-US", &["en-US", "en"]),
    ("UY", "es-419", &["es-419", "es"]),
    ("UZ", "en-US", &["en-US", "en"]),
    ("VA", "it", &["it-IT", "it", "en-US", "en"]),
    ("VC", "en-GB", &["en-GB", "en-US", "en"]),
    ("VE", "es-419", &["es-419", "es"]),
    ("VG", "en-GB", &["en-GB", "en-US", "en"]),
    ("VI", "en-GB", &["en-GB", "en-US", "en"]),
    ("VN", "vi", &["vi-VN", "vi", "fr-FR", "fr", "en-US", "en"]),
    ("VU", "en-GB", &["en-GB", "en-US", "en"]),
    ("WF", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("WS", "en-GB", &["en-GB", "en-US", "en"]),
    ("XK", "sr", &["sr-RS", "sr", "en-US", "en"]),
    ("YE", "ar", &["ar", "en-US", "en"]),
    ("YT", "fr", &["fr-FR", "fr", "en-US", "en"]),
    ("ZA", "en-GB", &["en-GB", "en-US", "en"]),
    ("ZM", "en-GB", &["en-GB", "en-US", "en"]),
    ("ZW", "en-GB", &["en-GB", "en-US", "en"]),
];

/// The locale for an exit country, or `None` for a country we have no row for.
///
/// `None` rather than a silent en-US: the caller decides whether to fall back,
/// and a caller that logs the miss is how a missing row gets noticed.
pub fn for_country(code: &str) -> Option<Locale> {
    let code = code.trim();
    if code.len() != 2 {
        return None;
    }
    let upper = code.to_ascii_uppercase();
    BY_COUNTRY
        .binary_search_by(|(c, _, _)| c.cmp(&upper.as_str()))
        .ok()
        .map(|i| {
            let (_, ui, languages) = BY_COUNTRY[i];
            Locale { ui, languages }
        })
}

/// What a profile gets when the exit could not be resolved at all.
///
/// Not a neutral choice — it is the single most common browser locale, so a
/// profile that falls back joins the largest crowd rather than a small one.
pub const FALLBACK: Locale = Locale {
    ui: "en-US",
    languages: &["en-US", "en"],
};

/// The UI locales Chrome ships a .pak for. Sorted.
///
/// Nothing outside this list can be passed as `--lang`: ResourceBundle would
/// find no strings and fall back to en-US, giving a profile a UI locale that
/// silently disagrees with the languages it announces.
static SHIPPED: &[&str] = &[
    ",
  ",
    ",  
  ",
    "af",
    "am",
    "ar",
    "bg",
    "bn",
    "ca",
    "cs",
    "da",
    "de",
    "el",
    "en-GB",
    "en-US",
    "es",
    "es-419",
    "et",
    "fa",
    "fi",
    "fil",
    "fr",
    "gu",
    "he",
    "hi",
    "hr",
    "hu",
    "id",
    "it",
    "ja",
    "kn",
    "ko",
    "lt",
    "lv",
    "ml",
    "mr",
    "ms",
    "nb",
    "nl",
    "pl",
    "pt-BR",
    "pt-PT",
    "ro",
    "ru",
    "sk",
    "sl",
    "sr",
    "sv",
    "sw",
    "ta",
    "te",
    "th",
    "tr",
    "uk",
    "ur",
    "vi",
    "zh-CN",
    "zh-TW",
];

/// The shipped UI locale for a language tag — `CheckAndResolveLocale`,
/// ui/base/l10n/l10n_util.cc:408, transcribed.
///
/// Needed for profiles that pin their own languages: the table above answers
/// for a country, and this answers for `de-AT` or `es-MX`, which no country row
/// would produce. The two must not disagree, and
/// `resolution_agrees_with_the_generated_table` holds them together.
pub fn ui_locale_for(tag: Option<&str>) -> String {
    let Some(tag) = tag.map(str::trim).filter(|t| !t.is_empty()) else {
        return FALLBACK.ui.to_string();
    };
    // Chromium canonicalises to '-'; a tag arriving as de_DE is the same tag.
    let tag = tag.replace('_', "-");

    if SHIPPED.binary_search(&tag.as_str()).is_ok() {
        return tag;
    }

    let (lang, region) = match tag.split_once('-') {
        Some((l, r)) => (l.to_ascii_lowercase(), Some(r.to_ascii_lowercase())),
        None => (tag.to_ascii_lowercase(), None),
    };

    if let Some(region) = region.as_deref() {
        let narrowed = match lang.as_str() {
            // :432 — es-RR other than es-ES is Latin American Spanish.
            "es" if region != "es" => "es-419".to_string(),
            // :440 — pt-RR other than pt-BR is European Portuguese.
            "pt" if region != "br" => "pt-PT".to_string(),
            // :446 — Hong Kong and Macao take Traditional, everything else
            // Simplified.
            "zh" => if region == "hk" || region == "mo" { "zh-TW" } else { "zh-CN" }.to_string(),
            // :454 — "Map Liberian and Filipino English to US English, and
            // everything else to British English."
            "en" => if region == "lr" || region == "ph" { "en-US" } else { "en-GB" }.to_string(),
            _ => lang.clone(),
        };
        if SHIPPED.binary_search(&narrowed.as_str()).is_ok() {
            return narrowed;
        }
    }

    // kAliasMap, :475. "Google updater uses no, tl, iw and en for our nb, fil,
    // he, and en-US."
    let aliased = match lang.as_str() {
        "en" => Some("en-US"),
        "iw" => Some("he"),
        "no" => Some("nb"),
        "pt" => Some("pt-BR"),
        "tl" => Some("fil"),
        "zh" => Some("zh-CN"),
        _ => None,
    };
    if let Some(a) = aliased {
        if SHIPPED.binary_search(&a).is_ok() {
            return a.to_string();
        }
    }
    if SHIPPED.binary_search(&lang.as_str()).is_ok() {
        return lang;
    }
    // :568 — "Fallback on en-US."
    FALLBACK.ui.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_sorted_and_unique() {
        // binary_search_by depends on it, and a generator bug would otherwise
        // show up as a country that silently has no row.
        for pair in BY_COUNTRY.windows(2) {
            assert!(
                pair[0].0 < pair[1].0,
                "{} and {} are out of order or duplicated",
                pair[0].0,
                pair[1].0
            );
        }
    }

    #[test]
    fn every_row_has_a_language() {
        for (country, ui, langs) in BY_COUNTRY {
            assert!(!langs.is_empty(), "{country} has no languages");
            assert!(!ui.is_empty(), "{country} has no ui locale");
            // A list whose first entry is not a real tag would reach
            // Accept-Language generation and produce a malformed header.
            assert!(
                langs[0].len() >= 2 && langs[0].is_ascii(),
                "{country} starts with {:?}",
                langs[0]
            );
        }
    }

    #[test]
    fn lookup_is_case_insensitive_and_rejects_nonsense() {
        assert_eq!(for_country("de"), for_country("DE"));
        assert!(for_country("DE").is_some());
        assert!(for_country("").is_none());
        assert!(for_country("D").is_none());
        assert!(for_country("DEU").is_none());
        assert!(for_country("ZZ").is_none());
    }

    #[test]
    fn the_rows_agree_with_chrome() {
        // Spot checks against values read out of the Chromium tree by hand, so
        // a generator that starts emitting plausible nonsense is caught.
        let de = for_country("DE").unwrap();
        assert_eq!(de.ui, "de");
        assert_eq!(de.languages, &["de-DE", "de", "en-US", "en"]);

        // Latin America is not Spain: CheckAndResolveLocale maps es-RR to
        // es-419, whose list is just "es-419,es" with no English at all.
        let mx = for_country("MX").unwrap();
        assert_eq!(mx.ui, "es-419");
        assert_eq!(mx.languages, &["es-419", "es"]);

        // Brazil keeps its own locale; Portugal takes pt-PT.
        assert_eq!(for_country("BR").unwrap().ui, "pt-BR");
        assert_eq!(for_country("PT").unwrap().ui, "pt-PT");

        // en-AU has no .pak, and Chrome maps it to British rather than US.
        // Australia only reaches English through CLDR's `de_facto_official`,
        // so a table built by counting `official` alone loses it.
        assert_eq!(for_country("AU").unwrap().ui, "en-GB");
        assert_eq!(for_country("US").unwrap().ui, "en-US");
    }

    #[test]
    fn a_country_chrome_ships_no_ui_for_gets_english() {
        // Albania's own language is official and real, and Chrome ships no
        // sq.pak on desktop — sq is in `extended_locales`. The first version of
        // this table sent it `--lang=sq` anyway, and a --lang with no .pak
        // behind it is a value that cannot be true: ResourceBundle silently
        // falls back to en-US.
        //
        // The second version fixed the .pak set and then walked past Albanian
        // to the next language CLDR lists for Albania, which is Greek. A
        // browser announcing Greek from a Tirana exit is a worse answer than an
        // English one, and stated with the same confidence. Both are pinned
        // here because both were shipped.
        for country in ["AL", "AM", "GE", "AZ", "IS", "MN"] {
            let l = for_country(country).unwrap();
            assert_eq!(l.ui, "en-US", "{country} should have an English browser");
            assert_eq!(l.languages, &["en-US", "en"]);
        }

        // Hong Kong is the opposite mistake: zh-HK ships no desktop .pak, but
        // Chrome has a rule for it — zh-HK and zh-MO map to Traditional — so
        // the answer is a Chinese browser, not an English one.
        let hk = for_country("HK").unwrap();
        assert_eq!(hk.ui, "zh-TW");
        assert_eq!(hk.languages, &["zh-TW", "zh", "en-US", "en"]);
    }

    #[test]
    fn resolution_agrees_with_the_generated_table() {
        // Two implementations of CheckAndResolveLocale exist — the generator's,
        // which built the table, and `ui_locale_for`, which answers at runtime.
        // Every UI locale the table chose must be a fixed point of the runtime
        // one, or a profile that pins its languages gets a different .pak from
        // one that follows its exit to the same place.
        for (country, ui, _) in BY_COUNTRY {
            assert_eq!(
                &ui_locale_for(Some(ui)),
                ui,
                "{country}: the table chose {ui} and the resolver moved it"
            );
            assert!(
                SHIPPED.binary_search(ui).is_ok(),
                "{country}: {ui} is not a locale Chrome ships a .pak for"
            );
        }
    }

    #[test]
    fn a_pinned_language_resolves_the_way_chrome_would() {
        // The cases the country table can never produce, because no country
        // maps to them — someone typed them into the profile.
        assert_eq!(ui_locale_for(Some("de-AT")), "de");
        assert_eq!(ui_locale_for(Some("es-MX")), "es-419");
        assert_eq!(ui_locale_for(Some("es-ES")), "es");
        assert_eq!(ui_locale_for(Some("pt-AO")), "pt-PT");
        assert_eq!(ui_locale_for(Some("pt")), "pt-BR");
        assert_eq!(ui_locale_for(Some("zh-MO")), "zh-TW");
        assert_eq!(ui_locale_for(Some("zh-SG")), "zh-CN");
        assert_eq!(ui_locale_for(Some("en-PH")), "en-US");
        assert_eq!(ui_locale_for(Some("en-IE")), "en-GB");
        assert_eq!(ui_locale_for(Some("no")), "nb");
        assert_eq!(ui_locale_for(Some("iw")), "he");
        assert_eq!(ui_locale_for(Some("de_DE")), "de");

        // A language Chrome ships no UI for. en-US rather than a .pak that does
        // not exist — Chromium's own last resort, l10n_util.cc:568.
        assert_eq!(ui_locale_for(Some("tlh")), "en-US");
        assert_eq!(ui_locale_for(None), "en-US");
        assert_eq!(ui_locale_for(Some("   ")), "en-US");
    }

    #[test]
    fn shipped_is_sorted() {
        // binary_search in ui_locale_for depends on it, and an unsorted list
        // fails by returning en-US for locales that do ship.
        for pair in SHIPPED.windows(2) {
            assert!(pair[0] < pair[1], "{} and {} out of order", pair[0], pair[1]);
        }
    }
}
