#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright 2026 Bogdan Shapovalov and the Fury authors
"""Generate deploy/workspace.toml from the repository's Cargo.toml.

    ./gen-deploy-workspace.py            write it
    ./gen-deploy-workspace.py --check    fail if it is out of date

A server is built from four directories — server/, shared-rs/, shared/,
deploy/ — and needs a workspace manifest that lists only the two crates that
travel. The repository's own manifest cannot be used as it stands: it lists
agent, desktop/src-tauri and tools/detect-suite, none of which are sent, and
cargo refuses a member it cannot find.

So there is a second manifest, and until now it was a copy typed into
server-install.sh by hand. That copy drifts, and it drifts silently: adding a
dependency to the workspace root works locally, passes every test, and breaks
the next deployment with

    error inheriting `digest` from workspace root manifest's
    `workspace.dependencies`

which is eight lines into cargo's output and points at nothing anybody would
connect to a shell script. It happened, which is why this exists.

Generated instead: [workspace.package] and [workspace.dependencies] come from
the repository verbatim, and only the member list is ours. CI regenerates and
compares, so the drift is caught by a test rather than by a deployment.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE = ROOT / "Cargo.toml"
TARGET = ROOT / "deploy" / "workspace.toml"

# What actually travels. shared/ is data rather than a crate — shared-rs
# include_str!s the personas out of it — so it is not a member.
MEMBERS = ["server", "shared-rs"]

HEADER = """# GENERATED by tools/ci/gen-deploy-workspace.py — do not edit.
#
# The workspace manifest a server is built with. Only two crates travel, so the
# member list is not the repository's; everything else is copied from it
# verbatim, because a hand-maintained copy drifts and the drift only shows up
# as a failed deployment.
#
# Regenerate after changing [workspace.dependencies] in the root Cargo.toml:
#     python3 tools/ci/gen-deploy-workspace.py
"""


def section(text: str, name: str) -> str:
    """One `[name]` block, verbatim, up to the next top-level header."""
    m = re.search(rf"^\[{re.escape(name)}\]$", text, re.M)
    if not m:
        raise SystemExit(f"no [{name}] in {SOURCE}")
    rest = text[m.end():]
    nxt = re.search(r"^\[", rest, re.M)
    body = rest[: nxt.start()] if nxt else rest
    return f"[{name}]\n{body.strip()}\n"


def render() -> str:
    src = SOURCE.read_text()
    members = "\n".join(f'    "{m}",' for m in MEMBERS)
    return (
        f"{HEADER}\n"
        f'[workspace]\nresolver = "2"\nmembers = [\n{members}\n]\n\n'
        f"{section(src, 'workspace.package')}\n"
        f"{section(src, 'workspace.dependencies')}\n"
        f'[profile.release]\nlto = "thin"\ncodegen-units = 1\nstrip = true\n'
    )


def main() -> int:
    want = render()
    if "--check" in sys.argv:
        have = TARGET.read_text() if TARGET.exists() else ""
        if have != want:
            print(
                f"!! {TARGET.relative_to(ROOT)} is out of date — run "
                f"tools/ci/gen-deploy-workspace.py",
                file=sys.stderr,
            )
            return 1
        print(f"{TARGET.relative_to(ROOT)} matches the workspace manifest")
        return 0

    TARGET.write_text(want)
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
